//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace SA_Zasoby {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class S5Data {
        
        private S5DataZasoba[] zasobaListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Zasoba", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public S5DataZasoba[] ZasobaList {
            get {
                return this.zasobaListField;
            }
            set {
                this.zasobaListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasoba {
        
        private group groupField;
        
        private string aktualniStav_IDField;
        
        private string artikl_IDField;
        
        private string canGetDataFromGroupField;
        
        private string druhArtiklu_IDField;
        
        private string druhKonta_IDField;
        
        private string historickaCenaField;
        
        private string jednotka_IDField;
        
        private string kodField;
        
        private string nazevField;
        
        private string objednanoField;
        
        private System.DateTime posledniNakupField;
        
        private bool posledniNakupFieldSpecified;
        
        private System.DateTime posledniProdejField;
        
        private bool posledniProdejFieldSpecified;
        
        private string radaObdobi_IDField;
        
        private string rezervovanoField;
        
        private string sklad_IDField;
        
        private string skladovaPozice_IDField;
        
        private string source_IDField;
        
        private enum_TypUctu typKontaField;
        
        private enum_TypZmenyPohybu typZmenyPohybuField;
        
        private string zasobaObratovaField;
        
        private string zasobaPojistnaField;
        
        private S5DataZasobaNastaveniZasoby nastaveniZasobyField;
        
        private S5DataZasobaAktualniStav aktualniStavField;
        
        private S5DataZasobaArtikl artiklField;
        
        private S5DataZasobaCinnosti cinnostiField;
        
        private S5DataZasobaDetaily detailyField;
        
        private S5DataZasobaDruhArtiklu druhArtikluField;
        
        private S5DataZasobaDruhKonta druhKontaField;
        
        private S5DataZasobaJednotka jednotkaField;
        
        private S5DataZasobaPohyby pohybyField;
        
        private S5DataZasobaRadaObdobi radaObdobiField;
        
        private S5DataZasobaSklad skladField;
        
        private S5DataZasobaSkladovaPozice skladovaPoziceField;
        
        private S5DataZasobaStavy stavyField;
        
        private string objectNameField;
        
        private string objectTypeField;
        
        private string idField;
        
        public S5DataZasoba() {
            this.objectNameField = "Zasoba";
            this.objectTypeField = "Object";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public group Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AktualniStav_ID {
            get {
                return this.aktualniStav_IDField;
            }
            set {
                this.aktualniStav_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Artikl_ID {
            get {
                return this.artikl_IDField;
            }
            set {
                this.artikl_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanGetDataFromGroup {
            get {
                return this.canGetDataFromGroupField;
            }
            set {
                this.canGetDataFromGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DruhArtiklu_ID {
            get {
                return this.druhArtiklu_IDField;
            }
            set {
                this.druhArtiklu_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DruhKonta_ID {
            get {
                return this.druhKonta_IDField;
            }
            set {
                this.druhKonta_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HistorickaCena {
            get {
                return this.historickaCenaField;
            }
            set {
                this.historickaCenaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Jednotka_ID {
            get {
                return this.jednotka_IDField;
            }
            set {
                this.jednotka_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nazev {
            get {
                return this.nazevField;
            }
            set {
                this.nazevField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Objednano {
            get {
                return this.objednanoField;
            }
            set {
                this.objednanoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime PosledniNakup {
            get {
                return this.posledniNakupField;
            }
            set {
                this.posledniNakupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PosledniNakupSpecified {
            get {
                return this.posledniNakupFieldSpecified;
            }
            set {
                this.posledniNakupFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime PosledniProdej {
            get {
                return this.posledniProdejField;
            }
            set {
                this.posledniProdejField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PosledniProdejSpecified {
            get {
                return this.posledniProdejFieldSpecified;
            }
            set {
                this.posledniProdejFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RadaObdobi_ID {
            get {
                return this.radaObdobi_IDField;
            }
            set {
                this.radaObdobi_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Rezervovano {
            get {
                return this.rezervovanoField;
            }
            set {
                this.rezervovanoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sklad_ID {
            get {
                return this.sklad_IDField;
            }
            set {
                this.sklad_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SkladovaPozice_ID {
            get {
                return this.skladovaPozice_IDField;
            }
            set {
                this.skladovaPozice_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Source_ID {
            get {
                return this.source_IDField;
            }
            set {
                this.source_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enum_TypUctu TypKonta {
            get {
                return this.typKontaField;
            }
            set {
                this.typKontaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enum_TypZmenyPohybu TypZmenyPohybu {
            get {
                return this.typZmenyPohybuField;
            }
            set {
                this.typZmenyPohybuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZasobaObratova {
            get {
                return this.zasobaObratovaField;
            }
            set {
                this.zasobaObratovaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZasobaPojistna {
            get {
                return this.zasobaPojistnaField;
            }
            set {
                this.zasobaPojistnaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaNastaveniZasoby NastaveniZasoby {
            get {
                return this.nastaveniZasobyField;
            }
            set {
                this.nastaveniZasobyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaAktualniStav AktualniStav {
            get {
                return this.aktualniStavField;
            }
            set {
                this.aktualniStavField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaArtikl Artikl {
            get {
                return this.artiklField;
            }
            set {
                this.artiklField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaCinnosti Cinnosti {
            get {
                return this.cinnostiField;
            }
            set {
                this.cinnostiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaDetaily Detaily {
            get {
                return this.detailyField;
            }
            set {
                this.detailyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaDruhArtiklu DruhArtiklu {
            get {
                return this.druhArtikluField;
            }
            set {
                this.druhArtikluField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaDruhKonta DruhKonta {
            get {
                return this.druhKontaField;
            }
            set {
                this.druhKontaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaJednotka Jednotka {
            get {
                return this.jednotkaField;
            }
            set {
                this.jednotkaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaPohyby Pohyby {
            get {
                return this.pohybyField;
            }
            set {
                this.pohybyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaRadaObdobi RadaObdobi {
            get {
                return this.radaObdobiField;
            }
            set {
                this.radaObdobiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaSklad Sklad {
            get {
                return this.skladField;
            }
            set {
                this.skladField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaSkladovaPozice SkladovaPozice {
            get {
                return this.skladovaPoziceField;
            }
            set {
                this.skladovaPoziceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaStavy Stavy {
            get {
                return this.stavyField;
            }
            set {
                this.stavyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class group {
        
        private string idField;
        
        private string kodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enum_ZpusobOcenovaniZasob {
        
        private enum_ZpusobOcenovaniZasobEnumValueName enumValueNameField;
        
        private bool enumValueNameFieldSpecified;
        
        private enum_ZpusobOcenovaniZasob_value valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public enum_ZpusobOcenovaniZasobEnumValueName EnumValueName {
            get {
                return this.enumValueNameField;
            }
            set {
                this.enumValueNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnumValueNameSpecified {
            get {
                return this.enumValueNameFieldSpecified;
            }
            set {
                this.enumValueNameFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public enum_ZpusobOcenovaniZasob_value Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum enum_ZpusobOcenovaniZasobEnumValueName {
        
        /// <remarks/>
        FIFO,
        
        /// <remarks/>
        VazenyPrumer,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    public enum enum_ZpusobOcenovaniZasob_value {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enum_VydejDoMinusu {
        
        private enum_VydejDoMinusuEnumValueName enumValueNameField;
        
        private bool enumValueNameFieldSpecified;
        
        private enum_VydejDoMinusu_value valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public enum_VydejDoMinusuEnumValueName EnumValueName {
            get {
                return this.enumValueNameField;
            }
            set {
                this.enumValueNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnumValueNameSpecified {
            get {
                return this.enumValueNameFieldSpecified;
            }
            set {
                this.enumValueNameFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public enum_VydejDoMinusu_value Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum enum_VydejDoMinusuEnumValueName {
        
        /// <remarks/>
        Nekontrolovat,
        
        /// <remarks/>
        Upozornit,
        
        /// <remarks/>
        Nepovolit,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    public enum enum_VydejDoMinusu_value {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enum_VyberDodavky {
        
        private enum_VyberDodavkyEnumValueName enumValueNameField;
        
        private bool enumValueNameFieldSpecified;
        
        private enum_VyberDodavky_value valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public enum_VyberDodavkyEnumValueName EnumValueName {
            get {
                return this.enumValueNameField;
            }
            set {
                this.enumValueNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnumValueNameSpecified {
            get {
                return this.enumValueNameFieldSpecified;
            }
            set {
                this.enumValueNameFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public enum_VyberDodavky_value Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum enum_VyberDodavkyEnumValueName {
        
        /// <remarks/>
        NejnizsiDatum,
        
        /// <remarks/>
        NejvyssiDatum,
        
        /// <remarks/>
        DatumExspirace,
        
        /// <remarks/>
        NejvyssiCena,
        
        /// <remarks/>
        NejnizsiCena,
        
        /// <remarks/>
        NejvyssiMnozstvi,
        
        /// <remarks/>
        NejnizsiMnozstvi,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    public enum enum_VyberDodavky_value {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enum_PridaniPolozkySDetailem {
        
        private enum_PridaniPolozkySDetailemEnumValueName enumValueNameField;
        
        private bool enumValueNameFieldSpecified;
        
        private enum_PridaniPolozkySDetailem_value valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public enum_PridaniPolozkySDetailemEnumValueName EnumValueName {
            get {
                return this.enumValueNameField;
            }
            set {
                this.enumValueNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnumValueNameSpecified {
            get {
                return this.enumValueNameFieldSpecified;
            }
            set {
                this.enumValueNameFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public enum_PridaniPolozkySDetailem_value Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum enum_PridaniPolozkySDetailemEnumValueName {
        
        /// <remarks/>
        StandardniChovani,
        
        /// <remarks/>
        VybratDetail,
        
        /// <remarks/>
        PridatMnozstvi,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    public enum enum_PridaniPolozkySDetailem_value {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enum_TypKontroly {
        
        private enum_TypKontrolyEnumValueName enumValueNameField;
        
        private bool enumValueNameFieldSpecified;
        
        private enum_TypKontroly_value valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public enum_TypKontrolyEnumValueName EnumValueName {
            get {
                return this.enumValueNameField;
            }
            set {
                this.enumValueNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnumValueNameSpecified {
            get {
                return this.enumValueNameFieldSpecified;
            }
            set {
                this.enumValueNameFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public enum_TypKontroly_value Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum enum_TypKontrolyEnumValueName {
        
        /// <remarks/>
        Nekontrolovat,
        
        /// <remarks/>
        Upozornit,
        
        /// <remarks/>
        Nepovolit,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    public enum enum_TypKontroly_value {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enum_NedostatecneMnozstviKVyrizeni {
        
        private enum_NedostatecneMnozstviKVyrizeniEnumValueName enumValueNameField;
        
        private bool enumValueNameFieldSpecified;
        
        private enum_NedostatecneMnozstviKVyrizeni_value valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public enum_NedostatecneMnozstviKVyrizeniEnumValueName EnumValueName {
            get {
                return this.enumValueNameField;
            }
            set {
                this.enumValueNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnumValueNameSpecified {
            get {
                return this.enumValueNameFieldSpecified;
            }
            set {
                this.enumValueNameFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public enum_NedostatecneMnozstviKVyrizeni_value Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum enum_NedostatecneMnozstviKVyrizeniEnumValueName {
        
        /// <remarks/>
        PonechatBezeZmeny,
        
        /// <remarks/>
        SnizitMnozstvi,
        
        /// <remarks/>
        OdebratPolozku,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    public enum enum_NedostatecneMnozstviKVyrizeni_value {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enum_TypZmenyPohybu {
        
        private enum_TypZmenyPohybuEnumValueName enumValueNameField;
        
        private bool enumValueNameFieldSpecified;
        
        private enum_TypZmenyPohybu_value valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public enum_TypZmenyPohybuEnumValueName EnumValueName {
            get {
                return this.enumValueNameField;
            }
            set {
                this.enumValueNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnumValueNameSpecified {
            get {
                return this.enumValueNameFieldSpecified;
            }
            set {
                this.enumValueNameFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public enum_TypZmenyPohybu_value Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum enum_TypZmenyPohybuEnumValueName {
        
        /// <remarks/>
        Prepis,
        
        /// <remarks/>
        Storno,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    public enum enum_TypZmenyPohybu_value {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enum_TypUctu {
        
        private enum_TypUctuEnumValueName enumValueNameField;
        
        private bool enumValueNameFieldSpecified;
        
        private enum_TypUctu_value valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public enum_TypUctuEnumValueName EnumValueName {
            get {
                return this.enumValueNameField;
            }
            set {
                this.enumValueNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnumValueNameSpecified {
            get {
                return this.enumValueNameFieldSpecified;
            }
            set {
                this.enumValueNameFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public enum_TypUctu_value Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum enum_TypUctuEnumValueName {
        
        /// <remarks/>
        Aktivni,
        
        /// <remarks/>
        Pasivni,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    public enum enum_TypUctu_value {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaNastaveniZasoby {
        
        private enum_NedostatecneMnozstviKVyrizeni nastaveniNedostatecneMnozstviKVyrizeniField;
        
        private enum_TypKontroly poklesPodPojistnouZasobuField;
        
        private enum_TypKontroly prekroceniObratoveZasobyField;
        
        private enum_PridaniPolozkySDetailem pridaniPolozkySDetailemField;
        
        private enum_VyberDodavky vyberDodavkyField;
        
        private enum_VydejDoMinusu vydejDoMinusuField;
        
        private enum_VydejDoMinusu vydejMnozstviKDispoziciField;
        
        private enum_ZpusobOcenovaniZasob zpusobOcenovaniField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enum_NedostatecneMnozstviKVyrizeni NastaveniNedostatecneMnozstviKVyrizeni {
            get {
                return this.nastaveniNedostatecneMnozstviKVyrizeniField;
            }
            set {
                this.nastaveniNedostatecneMnozstviKVyrizeniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enum_TypKontroly PoklesPodPojistnouZasobu {
            get {
                return this.poklesPodPojistnouZasobuField;
            }
            set {
                this.poklesPodPojistnouZasobuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enum_TypKontroly PrekroceniObratoveZasoby {
            get {
                return this.prekroceniObratoveZasobyField;
            }
            set {
                this.prekroceniObratoveZasobyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enum_PridaniPolozkySDetailem PridaniPolozkySDetailem {
            get {
                return this.pridaniPolozkySDetailemField;
            }
            set {
                this.pridaniPolozkySDetailemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enum_VyberDodavky VyberDodavky {
            get {
                return this.vyberDodavkyField;
            }
            set {
                this.vyberDodavkyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enum_VydejDoMinusu VydejDoMinusu {
            get {
                return this.vydejDoMinusuField;
            }
            set {
                this.vydejDoMinusuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enum_VydejDoMinusu VydejMnozstviKDispozici {
            get {
                return this.vydejMnozstviKDispoziciField;
            }
            set {
                this.vydejMnozstviKDispoziciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public enum_ZpusobOcenovaniZasob ZpusobOcenovani {
            get {
                return this.zpusobOcenovaniField;
            }
            set {
                this.zpusobOcenovaniField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaAktualniStav {
        
        private string objectNameField;
        
        private string objectTypeField;
        
        private string idField;
        
        public S5DataZasobaAktualniStav() {
            this.objectNameField = "StavZasoby";
            this.objectTypeField = "Object";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaArtikl {
        
        private group groupField;
        
        private string katalogField;
        
        private string objectNameField;
        
        private string objectTypeField;
        
        private string idField;
        
        public S5DataZasobaArtikl() {
            this.objectNameField = "Artikl";
            this.objectTypeField = "Object";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public group Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Katalog {
            get {
                return this.katalogField;
            }
            set {
                this.katalogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaCinnosti {
        
        private S5DataZasobaCinnostiArtiklCinnost[] artiklCinnostField;
        
        private string objectNameField;
        
        private string objectTypeField;
        
        public S5DataZasobaCinnosti() {
            this.objectNameField = "ArtiklCinnost";
            this.objectTypeField = "List";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ArtiklCinnost", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaCinnostiArtiklCinnost[] ArtiklCinnost {
            get {
                return this.artiklCinnostField;
            }
            set {
                this.artiklCinnostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaCinnostiArtiklCinnost {
        
        private string cinnost_IDField;
        
        private string poradiField;
        
        private S5DataZasobaCinnostiArtiklCinnostCinnost cinnostField;
        
        private string objectNameField;
        
        private string objectTypeField;
        
        private string idField;
        
        public S5DataZasobaCinnostiArtiklCinnost() {
            this.objectNameField = "ArtiklCinnost";
            this.objectTypeField = "Object";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cinnost_ID {
            get {
                return this.cinnost_IDField;
            }
            set {
                this.cinnost_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Poradi {
            get {
                return this.poradiField;
            }
            set {
                this.poradiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaCinnostiArtiklCinnostCinnost Cinnost {
            get {
                return this.cinnostField;
            }
            set {
                this.cinnostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaCinnostiArtiklCinnostCinnost {
        
        private string objectNameField;
        
        private string objectTypeField;
        
        private string idField;
        
        public S5DataZasobaCinnostiArtiklCinnostCinnost() {
            this.objectNameField = "Cinnost";
            this.objectTypeField = "Object";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaDetaily {
        
        private S5DataZasobaDetailyZasobaDetail[] zasobaDetailField;
        
        private string objectNameField;
        
        private string objectTypeField;
        
        public S5DataZasobaDetaily() {
            this.objectNameField = "ZasobaDetail";
            this.objectTypeField = "List";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZasobaDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaDetailyZasobaDetail[] ZasobaDetail {
            get {
                return this.zasobaDetailField;
            }
            set {
                this.zasobaDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaDetailyZasobaDetail {
        
        private string objectNameField;
        
        private string objectTypeField;
        
        private string idField;
        
        public S5DataZasobaDetailyZasobaDetail() {
            this.objectNameField = "ZasobaDetail";
            this.objectTypeField = "Object";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaDruhArtiklu {
        
        private string objectNameField;
        
        private string objectTypeField;
        
        private string idField;
        
        public S5DataZasobaDruhArtiklu() {
            this.objectNameField = "DruhArtiklu";
            this.objectTypeField = "Object";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaDruhKonta {
        
        private string objectNameField;
        
        private string objectTypeField;
        
        private string idField;
        
        public S5DataZasobaDruhKonta() {
            this.objectNameField = "DruhKonta";
            this.objectTypeField = "Object";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaJednotka {
        
        private group groupField;
        
        private string objectNameField;
        
        private string objectTypeField;
        
        private string idField;
        
        public S5DataZasobaJednotka() {
            this.objectNameField = "Jednotka";
            this.objectTypeField = "Object";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public group Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaPohyby {
        
        private S5DataZasobaPohybyPohybZasoby[] pohybZasobyField;
        
        private string objectNameField;
        
        private string objectTypeField;
        
        public S5DataZasobaPohyby() {
            this.objectNameField = "PohybZasoby";
            this.objectTypeField = "List";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PohybZasoby", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaPohybyPohybZasoby[] PohybZasoby {
            get {
                return this.pohybZasobyField;
            }
            set {
                this.pohybZasobyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaPohybyPohybZasoby {
        
        private string objectNameField;
        
        private string objectTypeField;
        
        private string idField;
        
        public S5DataZasobaPohybyPohybZasoby() {
            this.objectNameField = "PohybZasoby";
            this.objectTypeField = "Object";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaRadaObdobi {
        
        private string objectNameField;
        
        private string objectTypeField;
        
        private string idField;
        
        public S5DataZasobaRadaObdobi() {
            this.objectNameField = "RadaObdobi";
            this.objectTypeField = "Object";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaSklad {
        
        private group groupField;
        
        private string kodField;
        
        private string objectNameField;
        
        private string objectTypeField;
        
        private string idField;
        
        public S5DataZasobaSklad() {
            this.objectNameField = "Sklad";
            this.objectTypeField = "Object";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public group Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaSkladovaPozice {
        
        private string objectNameField;
        
        private string objectTypeField;
        
        private string idField;
        
        public S5DataZasobaSkladovaPozice() {
            this.objectNameField = "SkladovaPozice";
            this.objectTypeField = "Object";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaStavy {
        
        private S5DataZasobaStavyStavZasoby[] stavZasobyField;
        
        private string objectNameField;
        
        private string objectTypeField;
        
        public S5DataZasobaStavy() {
            this.objectNameField = "StavZasoby";
            this.objectTypeField = "List";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StavZasoby", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaStavyStavZasoby[] StavZasoby {
            get {
                return this.stavZasobyField;
            }
            set {
                this.stavZasobyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaStavyStavZasoby {
        
        private string konto_IDField;
        
        private string obdobi_IDField;
        
        private string odchylkaField;
        
        private string soucetField;
        
        private string uzaverkaObdobi_IDField;
        
        private S5DataZasobaStavyStavZasobyObrat obratField;
        
        private S5DataZasobaStavyStavZasobyPocatek pocatekField;
        
        private S5DataZasobaStavyStavZasobyPrirustek prirustekField;
        
        private S5DataZasobaStavyStavZasobyUbytek ubytekField;
        
        private S5DataZasobaStavyStavZasobyZustatek zustatekField;
        
        private S5DataZasobaStavyStavZasobyKonto kontoField;
        
        private S5DataZasobaStavyStavZasobyObdobi obdobiField;
        
        private S5DataZasobaStavyStavZasobyUzaverkaObdobi uzaverkaObdobiField;
        
        private string objectNameField;
        
        private string objectTypeField;
        
        private string idField;
        
        public S5DataZasobaStavyStavZasoby() {
            this.objectNameField = "StavZasoby";
            this.objectTypeField = "Object";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Konto_ID {
            get {
                return this.konto_IDField;
            }
            set {
                this.konto_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Obdobi_ID {
            get {
                return this.obdobi_IDField;
            }
            set {
                this.obdobi_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Odchylka {
            get {
                return this.odchylkaField;
            }
            set {
                this.odchylkaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Soucet {
            get {
                return this.soucetField;
            }
            set {
                this.soucetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UzaverkaObdobi_ID {
            get {
                return this.uzaverkaObdobi_IDField;
            }
            set {
                this.uzaverkaObdobi_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaStavyStavZasobyObrat Obrat {
            get {
                return this.obratField;
            }
            set {
                this.obratField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaStavyStavZasobyPocatek Pocatek {
            get {
                return this.pocatekField;
            }
            set {
                this.pocatekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaStavyStavZasobyPrirustek Prirustek {
            get {
                return this.prirustekField;
            }
            set {
                this.prirustekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaStavyStavZasobyUbytek Ubytek {
            get {
                return this.ubytekField;
            }
            set {
                this.ubytekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaStavyStavZasobyZustatek Zustatek {
            get {
                return this.zustatekField;
            }
            set {
                this.zustatekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaStavyStavZasobyKonto Konto {
            get {
                return this.kontoField;
            }
            set {
                this.kontoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaStavyStavZasobyObdobi Obdobi {
            get {
                return this.obdobiField;
            }
            set {
                this.obdobiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public S5DataZasobaStavyStavZasobyUzaverkaObdobi UzaverkaObdobi {
            get {
                return this.uzaverkaObdobiField;
            }
            set {
                this.uzaverkaObdobiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaStavyStavZasobyObrat {
        
        private string celkovaCenaField;
        
        private string jednotkaCenaField;
        
        private string mnozstviField;
        
        private string pocetJednotekField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CelkovaCena {
            get {
                return this.celkovaCenaField;
            }
            set {
                this.celkovaCenaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string JednotkaCena {
            get {
                return this.jednotkaCenaField;
            }
            set {
                this.jednotkaCenaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mnozstvi {
            get {
                return this.mnozstviField;
            }
            set {
                this.mnozstviField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PocetJednotek {
            get {
                return this.pocetJednotekField;
            }
            set {
                this.pocetJednotekField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaStavyStavZasobyPocatek {
        
        private string celkovaCenaField;
        
        private string jednotkaCenaField;
        
        private string mnozstviField;
        
        private string pocetJednotekField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CelkovaCena {
            get {
                return this.celkovaCenaField;
            }
            set {
                this.celkovaCenaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string JednotkaCena {
            get {
                return this.jednotkaCenaField;
            }
            set {
                this.jednotkaCenaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mnozstvi {
            get {
                return this.mnozstviField;
            }
            set {
                this.mnozstviField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PocetJednotek {
            get {
                return this.pocetJednotekField;
            }
            set {
                this.pocetJednotekField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaStavyStavZasobyPrirustek {
        
        private string celkovaCenaField;
        
        private string jednotkaCenaField;
        
        private string mnozstviField;
        
        private string pocetJednotekField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CelkovaCena {
            get {
                return this.celkovaCenaField;
            }
            set {
                this.celkovaCenaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string JednotkaCena {
            get {
                return this.jednotkaCenaField;
            }
            set {
                this.jednotkaCenaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mnozstvi {
            get {
                return this.mnozstviField;
            }
            set {
                this.mnozstviField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PocetJednotek {
            get {
                return this.pocetJednotekField;
            }
            set {
                this.pocetJednotekField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaStavyStavZasobyUbytek {
        
        private string celkovaCenaField;
        
        private string jednotkaCenaField;
        
        private string mnozstviField;
        
        private string pocetJednotekField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CelkovaCena {
            get {
                return this.celkovaCenaField;
            }
            set {
                this.celkovaCenaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string JednotkaCena {
            get {
                return this.jednotkaCenaField;
            }
            set {
                this.jednotkaCenaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mnozstvi {
            get {
                return this.mnozstviField;
            }
            set {
                this.mnozstviField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PocetJednotek {
            get {
                return this.pocetJednotekField;
            }
            set {
                this.pocetJednotekField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaStavyStavZasobyZustatek {
        
        private string celkovaCenaField;
        
        private string jednotkaCenaField;
        
        private string mnozstviField;
        
        private string pocetJednotekField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CelkovaCena {
            get {
                return this.celkovaCenaField;
            }
            set {
                this.celkovaCenaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string JednotkaCena {
            get {
                return this.jednotkaCenaField;
            }
            set {
                this.jednotkaCenaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mnozstvi {
            get {
                return this.mnozstviField;
            }
            set {
                this.mnozstviField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PocetJednotek {
            get {
                return this.pocetJednotekField;
            }
            set {
                this.pocetJednotekField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaStavyStavZasobyKonto {
        
        private string objectNameField;
        
        private string objectTypeField;
        
        private string idField;
        
        public S5DataZasobaStavyStavZasobyKonto() {
            this.objectNameField = "Konto";
            this.objectTypeField = "Object";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaStavyStavZasobyObdobi {
        
        private string objectNameField;
        
        private string objectTypeField;
        
        private string idField;
        
        public S5DataZasobaStavyStavZasobyObdobi() {
            this.objectNameField = "Obdobi";
            this.objectTypeField = "Object";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class S5DataZasobaStavyStavZasobyUzaverkaObdobi {
        
        private string objectNameField;
        
        private string objectTypeField;
        
        private string idField;
        
        public S5DataZasobaStavyStavZasobyUzaverkaObdobi() {
            this.objectNameField = "UzaverkaObdobi";
            this.objectTypeField = "Object";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
}
