#!/bin/bash
DATA='<!--ADDED BY SCRIPT-->
    <xs:element name="ObsahPolozky" minOccurs="0">
        <xs:complexType>
            <xs:all>
                <xs:element name="Artikl_ID" minOccurs="0" />
                <xs:element name="Sklad_ID" minOccurs="0" />
            </xs:all>
            <xs:attribute name="GENERATEZASOBA" type="string_60" />
        </xs:complexType>
    </xs:element>
<!--ADDED BY SCRIPT END-->'

ESCAPED=`echo "${DATA}" | sed -r ':a;N;$!ba;s|\n|\\\|g' | sed 's|/|\\\/|g'`

for n in xsd/*.xsd; do 
    sed -i -r "s/^.+ObsahPolozky_ID.+$/${ESCAPED}/mg" ${n} ;
    xsd ${n} /c /n:$(basename ${n} .xsd) /o:xsd-gen ;
done